#!/bin/sh

PROJECT_NAME="$1"
PROJECT_PATH="./projects/""$1""/"
SOURCE_PATH="./projects/""$1""/""$1""_grt_rtw/"
LIBRARY_PATH="./lib/"

# clean the project
if [ "$2" = "clean" ]; then
  echo "cleaning: removing objects and executables."
  rm $SOURCE_PATH*.o
  rm "$PROJECT_PATH/$PROJECT_NAME"
  exit
fi

# build object files
echo "Building: " $PROJECT_PATH
echo "Building object files."
gcc -c -std=c99 -pedantic -fwrapv -fPIC -O0 -DMAT_FILE=1 -DINTEGER_CODE=0 -DMT=0 -DCLASSIC_INTERFACE=0 -DALLOCATIONFCN=0 -DONESTEPFCN=1 -DTERMFCN=1 -DMULTI_INSTANCE_CODE=0 -DTID01EQ=0 -DMODEL=$PROJECT_NAME -DNUMST=1 -DNCSTATES=0 -DHAVESTDIO -DRT -DUSE_RTMODEL -DUNIX -I$PROJECT_PATH -I$LIBRARY_PATH -I$SOURCE_PATH  -o "$SOURCE_PATH/""$PROJECT_NAME"".o" "$SOURCE_PATH/""$PROJECT_NAME"".c" -lwiringPi
gcc -c -std=c99 -pedantic -fwrapv -fPIC -O0 -DMAT_FILE=1 -DINTEGER_CODE=0 -DMT=0 -DCLASSIC_INTERFACE=0 -DALLOCATIONFCN=0 -DONESTEPFCN=1 -DTERMFCN=1 -DMULTI_INSTANCE_CODE=0 -DTID01EQ=0 -DMODEL=$PROJECT_NAME -DNUMST=1 -DNCSTATES=0 -DHAVESTDIO -DRT -DUSE_RTMODEL -DUNIX -I$PROJECT_PATH -I$LIBRARY_PATH -I$SOURCE_PATH  -o "$SOURCE_PATH/""rtGetInf.o" "$SOURCE_PATH/""rtGetInf.c" -lwiringPi
gcc -c -std=c99 -pedantic -fwrapv -fPIC -O0 -DMAT_FILE=1 -DINTEGER_CODE=0 -DMT=0 -DCLASSIC_INTERFACE=0 -DALLOCATIONFCN=0 -DONESTEPFCN=1 -DTERMFCN=1 -DMULTI_INSTANCE_CODE=0 -DTID01EQ=0 -DMODEL=$PROJECT_NAME -DNUMST=1 -DNCSTATES=0 -DHAVESTDIO -DRT -DUSE_RTMODEL -DUNIX -I$PROJECT_PATH -I$LIBRARY_PATH -I$SOURCE_PATH  -o "$SOURCE_PATH/""rtGetNaN.o" "$SOURCE_PATH/""rtGetNaN.c" -lwiringPi
gcc -c -std=c99 -pedantic -fwrapv -fPIC -O0 -DMAT_FILE=1 -DINTEGER_CODE=0 -DMT=0 -DCLASSIC_INTERFACE=0 -DALLOCATIONFCN=0 -DONESTEPFCN=1 -DTERMFCN=1 -DMULTI_INSTANCE_CODE=0 -DTID01EQ=0 -DMODEL=$PROJECT_NAME -DNUMST=1 -DNCSTATES=0 -DHAVESTDIO -DRT -DUSE_RTMODEL -DUNIX -I$PROJECT_PATH -I$LIBRARY_PATH -I$SOURCE_PATH  -o "$SOURCE_PATH/""rt_nonfinite.o" "$SOURCE_PATH/""rt_nonfinite.c" -lwiringPi
gcc -c -std=c99 -pedantic -fwrapv -fPIC -O0 -DMAT_FILE=1 -DINTEGER_CODE=0 -DMT=0 -DCLASSIC_INTERFACE=0 -DALLOCATIONFCN=0 -DONESTEPFCN=1 -DTERMFCN=1 -DMULTI_INSTANCE_CODE=0 -DTID01EQ=0 -DMODEL=$PROJECT_NAME -DNUMST=1 -DNCSTATES=0 -DHAVESTDIO -DRT -DUSE_RTMODEL -DUNIX -I$PROJECT_PATH -I$LIBRARY_PATH -I$SOURCE_PATH  -o "$SOURCE_PATH/""rt_logging.o" "$LIBRARY_PATH/""rt_logging.c" -lwiringPi
gcc -c -std=c99 -pedantic -fwrapv -fPIC -O0 -DMAT_FILE=1 -DINTEGER_CODE=0 -DMT=0 -DCLASSIC_INTERFACE=0 -DALLOCATIONFCN=0 -DONESTEPFCN=1 -DTERMFCN=1 -DMULTI_INSTANCE_CODE=0 -DTID01EQ=0 -DMODEL=$PROJECT_NAME -DNUMST=1 -DNCSTATES=0 -DHAVESTDIO -DRT -DUSE_RTMODEL -DUNIX -I$PROJECT_PATH -I$LIBRARY_PATH -I$SOURCE_PATH  -o "$SOURCE_PATH/""rt_main.o" "$LIBRARY_PATH""rt_main.c" -lwiringPi

echo "Creating standalone executable."
gcc -Wl,-rpath,"/usr/local/MATLAB/R2017a/bin/glnxa64",-L"/usr/local/MATLAB/R2017a/bin/glnxa64" -o "$PROJECT_PATH""$PROJECT_NAME" "$SOURCE_PATH""$PROJECT_NAME"".o" "$SOURCE_PATH""rtGetInf.o" "$SOURCE_PATH""rtGetNaN.o" "$SOURCE_PATH""rt_nonfinite.o" "$SOURCE_PATH""rt_logging.o" "$SOURCE_PATH""rt_main.o" -lm
echo "done. executable is created at $PROJECT_PATH$PROJECT_NAME"
